webSPELL/webSPELL

admin/gallery.php
admin/page_statistic.php
admin/servers.php
admin/visitor_statistic_image.php
articles.php
clanwars.php
latesttopics.php
news.php
search.php
tags.php

Function calls inside for loop control statements are executed every time which is not needed in our case

fix(codestyle): remove function calls in loops

---

index.php

Ich habe mal die p Tags aus der index.php rausgenommen damit eine valide
HTML Ausgabe zustande kommt.
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/135%23issuecomment-69495212%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-11T13%3A54%3A44Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%5D%2C%20%22title%22%3A%20%22G …

fix(index): removed p tags

---

buddies.php

fixed a query failed if you readd or delete a buddy
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/156%23issuecomment-69524075%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/156%23issuecomment-69590963%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/156%23issuecomment-69595100%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/156%23issuecomment-69524075%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22Add%20a%20space%20before%20and%20after%20the%20%60.%60%20and%20I%20will%20merge%2C%20thank%20you.%5Cr%5Cn%5Cr%5Cn%60buddy%3D%27%5C%22%20.%20%28int%29%24_GET%5B%20%27id%27%20%5D.%5C%22%27%5C%22%60%20 …

fix(php) readd and delete buddy query failed fixed

---

forum_topic.php

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69835261%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69930556%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69930685%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69930981%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/170%23issuecomment-69835261%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22You%20should%20have%20done%20a%20rebase%20before%20committing%20the%20changes%20and%20open%20the%20PR.%5Cr%5CnThis%20would%20have%20avoided%20commit%2014de68dae7 …

fix(php) missing namespace added

---

Gruntfile.js
js/bbcode.js
karma.conf.js
package.json
tests/karma/bbcodeSpec.js

<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/173?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/173'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Karma (JS Unit Tests)

---

sc_squads.php
templates/sc_squads.html

- add img-responsive class to img
- badge removed
- bg removed
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%2C%20%22https%3A//github.com/xxxrenegade%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/2109906%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/174%23issuecomment-70377673%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-17T18%3A17%3A31Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3 …

fix(sc_squads): fix bootstrap adaptation

---

templates/sc_squads.html

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/179%23issuecomment-70702121%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-20T18%3A08%3A24Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3 …

fix(squads): squadname not displayed

---

templates/articles_post.html
templates/clanwar_new.html
templates/forum_newreply.html
templates/forum_newtopic.html
templates/forum_newtopic_iconlist.html
templates/myprofile.html
templates/news_post.html
templates/pm_incoming_content.html
templates/pm_outgoing_content.html
templates/poll_content.html
templates/polls_edit.html
templates/search_form_loggedin.html
templates/search_form_notloggedin.html
templates/upcoming_war_new.html

fixes #158
<a href='https://www.codereviewhub.com/webSPELL/webSPELL-4.2.3/pull/183?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL-4.2.3/pull/183'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

remove classes on radio and checkbox

---

awards.php
calendar.php
challenge.php
clanwars.php
demos.php

Dates can now be added from (now - 5 years) to (now + 1 year) or vise versa (which ever makes sense)
<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/184%23issuecomment-70893057%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/184%23issuecomment-70920035%22%2C%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/184%23issuecomment-71277856%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/184%23issuecomment-70893057%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22There%20are%20more%20date%20inputs%20like%20calendar%5Cr%5Cn%22%2C%20%22created_at%22%3A%20%222015-01-21T18%3A28%3A34Z%22%2C%20%22user%22%3A%20%7B%22 …

fix(date) make dates usable in the future

---

gallery.php
languages/de/members.php
languages/de/squads.php
languages/uk/members.php
languages/uk/squads.php
members.php
squads.php

closes #159
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/derchrisuk%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL-4.2.3/pull/187%23issuecomment-71707946%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-01-27T19%3A10%3A51Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPEL …

Added alert for Gallery, Squads and Members when no entries are available

---

templates/comments_edit.html
templates/guestbook_comment.html
templates/guestbook_loggedin.html
templates/pm_new_touser.html
templates/pm_reply.html
templates/upcoming_date_edit.html

fix #191
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/192%23issuecomment-72699345%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-02-03T17%3A52%3A12Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pu …

wip(codestyle) textarea indention

---

forum_topic.php

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Phhere%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/215%23issuecomment-84878365%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%20%22%2C%20%22created_at%22%3A%20%222015-03-23T08%3A15%3A15Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/215%2 …

fix(forum): always show latest posts in edit mode

---

install/functions.php

closes #222
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/229%23issuecomment-94408475%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-04-20T09%3A37%3A25Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL …

fix(install): add default utf charset/collate to create table

---

register.php
templates/register.html

<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/234?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/234'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

feat(register): remove password repeat, make input type password

---

Gruntfile.js
myprofile.php
package.json
src/func/filesystem.php

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Phhere%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/235%23issuecomment-99158376%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-05-05T17%3A55%3A06Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/235%23is …

feat(buildtools) add grunt-lintspaces

---

_functions.php
checklogin.php
src/login.php

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/240%23issuecomment-99356116%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-05-06T07%3A38%3A48Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/240%23 …

fix(login): be safe against timing attacks, closes #237

---

admin/visitor_statistic_image.php

The visitor_statistic_image threw errors while loading the language file. This way the language files will be loaded correctly (See https://github.com/webSPELL/webSPELL/blob/dev/admin/admincenter.php)
<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Phhere%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/246%23issuecomment-107999202%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-06-02T15%3A57%3A03Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C …

fix(visitor_statistic_image): fix path error with DirectoryIterator

---

checklogin.php
js/bbcode.js
templates/lock.html
templates/login.html

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Phhere%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/242%23issuecomment-108035758%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-06-02T18%3A06%3A27Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/1415280%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Phhere%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/242%23i …

Improve UX for Login

---

admin/ranks.php

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/255%23issuecomment-115188490%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-06-25T09%3A42%3A37Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/255%2 …

fix(admincenter): acp ranks view fix

---

admin/addons.php
admin/bannerrotation.php
admin/gallery.php
admin/modrewrite.php
admin/rubrics.php
admin/static.php
admin/update.php
admin/users.php

<a href='#crh-start'></a><a href='#crh-data-%7B%22approved%22%3A%20%7B%22https%3A//github.com/Pascalmh%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%7D%7D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/254%23issuecomment-115190371%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22%3Ashipit%3A%22%2C%20%22created_at%22%3A%20%222015-06-25T09%3A46%3A19Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/498197%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/Pascalmh%22%7D%7D%5D%2C%20%22title%22%3A%20%22General%20Comment%22%7D%7D%2C%20%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/254%2 …

fix(admincenter): add missing input class for buttons

---

index.php
templates/navigation.html

ref #99 - this does not fix this issue but I think it is a good first Iteration for this Issue.
<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/253?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/253'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

feat(index): put login into navigation for small devices

---

index.php

fix(index): show login on md and lg devices

---

admin/rubrics.php

Wie im Issue beschrieben,hier die Änderungen der rubrics.php, damit keine Fehler mehr kommen.
Fehler waren: Bei Upload einer neuer Rubrik, wird immer wieder das Bild, welches hochgeladen wurde für alle Rubriken genutzt.
<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/273?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/273'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

Änderungen in der rubrics.php

---

js/bbcode.js

fix(bbcode): corrected image resize per javascript

---

news.php
templates/news_post.html

<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/278?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/278'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fix(news): added missing select box for comments

---

news.php

<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/279?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/279'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fix(news): add img responsive to rubricpic

---

index.php

fixes #275
<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/280?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/280'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

feat(languages): add current language to html lang attribute

---

myprofile.php

closes #286
had the bug with password changing and fixed it.
<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/294?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/294'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fixed password change bug

---

comments.php

- fixing #299: the incorrect statement to update a comment
<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/300?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/300'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fix #299 update comments

---

demos.php

fix #303 
<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/305?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/305'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fix(demos): fatal error on demo creation

---

demos.php
src/func/language.php

<a href='#crh-start'></a><a href='#crh-data-%7B%22processed%22%3A%20%5B%22https%3A//github.com/webSPELL/webSPELL/pull/304%23issuecomment-175582039%22%2C%20%22https%3A//github.com/webSPELL/webSPELL/pull/304%23issuecomment-175589703%22%5D%2C%20%22comments%22%3A%20%7B%22General%20Comment%22%3A%20%7B%22html_url%22%3A%20%22https%3A//github.com/webSPELL/webSPELL/pull/304%23issuecomment-175582039%22%2C%20%22comments%22%3A%20%5B%7B%22body%22%3A%20%22This%20PR%20includes%20fixes%20for%202x%20different%20issues.%22%2C%20%22created_at%22%3A%20%222016-01-27T11%3A55%3A00Z%22%2C%20%22user%22%3A%20%7B%22avatar_url%22%3A%20%22https%3A//avatars.githubusercontent.com/u/706758%3Fv%3D3%22%2C%20%22html_url%22%3A%20%22https%3A//github.com/derchrisuk%22%7D%7D%2C%20%7B%22body%22%3A%20%22wtf%20-.-%20%5Cr%5Cn%5Cr%5 …

Update language.php (issues #302)

---

rating.php

fixed #307
<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/308?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/308'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fix(rating): sql query fixed (rating pic was displayed incorrectly)

---

cash_box.php

patch for sql injection reported by @HTBridge in #309
<a href='https://www.codereviewhub.com/webSPELL/webSPELL/pull/310?approve=1'><img src='http://www.codereviewhub.com/site/github-approve.png' height=26></a>&nbsp;<a href='https://github.com/webSPELL/webSPELL/pull/310'><img src='http://www.codereviewhub.com/site/github-refresh.png' height=26></a>

fix: sql injection
